---
# ============================================================================
#  Ansible Playbook: Secure Debian/Ubuntu Server Setup
# ============================================================================
#
#  Objetivo: Preparar um servidor mínimo e seguro para produção, com
#            foco em hardening e boas práticas, usando uma estrutura de roles
#            para modularidade.
#
#  Como executar:
#  ansible-playbook -i inventory.ini playbook.yml
#
# ============================================================================

- name: Preparar e Proteger Servidor Debian/Ubuntu
  hosts: servers
  become: yes
  vars:
    # --- Variáveis Gerais ---
    deploy_user: deploy
    swap_file_path: /swapfile
    # Define o tamanho do swap como 50% da RAM, com um mínimo de 1GB e um máximo de 4GB.
    swap_size_mb: "{{ ([1024, (ansible_memtotal_mb / 2) | int, 4096] | sort)[1] }}"

    # --- Variáveis das Aplicações (Imagens Docker) ---
    traefik_version: "v3.1.0"
    portainer_version: "2.20.1"
    prometheus_version: "v2.53.0"
    grafana_version: "11.1.0"
    jaeger_version: "1.57"

    # --- Variáveis de Domínio e Email (TROCAR ESTES VALORES) ---
    traefik_domain: "traefik.example.com"
    portainer_domain: "portainer.example.com"
    prometheus_domain: "prometheus.example.com"
    grafana_domain: "grafana.example.com"
    jaeger_domain: "jaeger.example.com"
    letsencrypt_email: "seu-email@example.com"

  roles:
    - role: common
    - role: docker
    - role: observability
