---
# tasks file for docker role
# Responsável pela instalação do Docker Engine e Docker Compose.

# --------------------------------------------------------------------------
# ETAPA 8: INSTALAÇÃO DO DOCKER ENGINE
# --------------------------------------------------------------------------
- name: "Adicionar chave GPG oficial do Docker"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  tags: [docker]

- name: "Adicionar repositório oficial do Docker"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  tags: [docker]

- name: "Instalar Docker Engine e plugins"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  tags: [docker]

- name: "Garantir que o serviço Docker está ativo e habilitado na inicialização"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags: [docker]

- name: "Configurar rotação de logs para o daemon do Docker"
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    mode: '0644'
  notify: Restart Docker
  tags: [docker]

# --------------------------------------------------------------------------
# ETAPA 9: GRUPO DOCKER E USUÁRIO
# --------------------------------------------------------------------------
- name: "Garantir que o grupo 'docker' existe"
  ansible.builtin.group:
    name: docker
    state: present
  tags: [docker]

- name: "Adicionar o usuário '{{ deploy_user }}' ao grupo 'docker'"
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes
  tags: [docker] 